
jobs:
  add_repo:
    runs-on: ubuntu-latest
    needs: build-debs
    strategy:
      max-parallel: 1
      matrix:
        os-version: ["buster", "bullseye", "bookworm", "noble", "jammy", "focal"]
        arch: ["amd64"]
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: "packages-${{ matrix.os-version }}-${{ matrix.arch }}"
      - name: Add ${{ matrix.arch }}/${{ matrix.os-version }} release
        uses: smeinecke/apt-repo-action@v2.1.4
        with:
          github_token: ${{ github.token }}
          repo_supported_arch: |
            amd64
          repo_supported_version: |
            buster
            bullseye
            bookworm
            noble
            jammy
            focal
          file: |
            *~${{ matrix.os-version }}*.deb
          file_target_version: ${{ matrix.os-version }}
          private_key: ${{ secrets.APT_SIGNING_KEY }}
          public_key: ${{ secrets.APT_SIGNING_PUBKEY }}
          key_passphrase: ${{ secrets.APT_SIGNING_KEY_PASSPHRASE }}
